### PR TITLE
NPM update

### PR DESCRIPTION
**Pull request by christopherpickering**
hey @changey 
issues are disabled on the repo so I'm doing a blank PR w/ an issue :)

Is it possible to update npm w/ v4? Right now only v3 is on npm, but v4 is needed to work with leaflet-react v4.

Can you consider enabling issues in GitHub? It would be easier than doing blank prs... thanks!

### CODE REVIEW

**Comment by Vacilando** [comment]
Same here 
- where is the NPM release?
- is this the official follower of https://github.com/yuzhva/react-leaflet-markercluster ?
- what are the development plans?
- why are issues disabled?

**Comment by christopherpickering** [comment]
fyi, I created npm package with updated docs and example using the latest leaflet...  real mess of npm packages, but no one seems to be interested in accepting pr's etc. https://www.npmjs.com/package/@christopherpickering/react-leaflet-markercluster

**Comment by uswant** [comment]
anyone know why everytime i setState (update new state) through mouseover() a marker, the spiderfier of clustermarker close automatically?

**Comment by christopherpickering** [comment]
@uswant Probably this problem: https://github.com/PaulLeCam/react-leaflet/issues/1049

**Comment by uswant** [comment]
> @uswant Probably this problem: [PaulLeCam/react-leaflet#1049](https://github.com/PaulLeCam/react-leaflet/issues/1049)

i guess the problem where i did mouseover() the marker its setState to display popup which not in leaflet-pane (outside leaflet-container) that's why the clustermarker close the spiderfier automatically. how do you think? any solution to solve this case? thankyou

**Pull request closed without merging**
